version: '3.8'

services:
  frontend:
    image: httpd:2.4  
    ports:
      - "8083:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/ 

   # API Service
  api:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www/html/ 

  
  # Database Service
  db:
    image: mysql:latest
    #restart: always
    env_file:
      - .env 
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      
volumes:
  db-data: