version: '3.8'

services:
  frontend:
    image: httpd:2.4  
    ports:
      - "8083:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/ 

  # API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile  
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html/  
    depends_on:
      - db
# Database Service
  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=au_temps_donnee
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

volumes:
  db-data:  


    # Database Service
    # db:
    #   image: mysql:5.7  
    #   volumes:
    #     - db-data:/var/lib/mysql  # Corrected: no space before the path
    #   environment:
    #     - MYSQL_ROOT_PASSWORD=root 
    #     - MYSQL_DATABASE=au_temps_donnee
    #     - MYSQL_USER=root
    #     - MYSQL_PASSWORD=root
    #   ports:
    #     - "3306:3306"