version: '3.9'

services:
  frontend:
    image: rg.fr-par.scw.cloud/namespace-temps-donne/ubuntu:dev
    ports:
      - "8083:80"
    volumes:
      - ./front:/var/www/html
    environment:
      - NODE_ENV=development
    command: npm start  # Assure le rechargement à chaud

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www/html
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=temps
    command: npm run dev  # Rechargement à chaud pour le développement

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: temps
    ports:
      - "3307:3306"
    volumes:
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql

volumes:
  db-data:
