version: '3.9'

services:
  # Frontend Service
  frontend:
    build:
      context: . 
      dockerfile: Dockerfile.prod
    image: rg.fr-par.scw.cloud/namespace-temps-donne/ubuntu:prod
    ports:
      - "80:80"  
    volumes:
      - ./front:/var/www/html/
    restart: unless-stopped

  # API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    ports:
      - "8082:80"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=toor
      - DB_NAME=temps
    restart: unless-stopped

  # Database Service
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: temps
    volumes:
      - db-data:/var/lib/mysql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql
    restart: unless-stopped

volumes:
  db-data:
