version: '3.8'

services:
  # Frontend Service
  frontend:
    image: php:8-apache
    ports:
      - "8083:80"
    volumes:
      - ./front:/var/www/html/

  # API Service
  api:
    build: .
    ports:
      - "8082:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
      - MYSQL_DATABASE=temps
      - JWT_SECRET_KEY=RPARYXfMrSHxsffextjzQ8PgrMAfUGq/zt36Q+Rac+Ps=
    volumes:
      - ./api:/var/www/html/

  # Database Service
  database:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=temps
      - MYSQL_USER=api
      - MYSQL_PASSWORD=toor
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8086:80"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=temps
      - MYSQL_USER=api
      - MYSQL_PASSWORD=toor
volumes:
  db-data:
