# Utilisation d'une image PHP avec Apache
FROM php:8-apache

# Installer les extensions nécessaires et autres dépendances
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*  

# Activer Xdebug pour le développement (facultatif)
RUN pecl install xdebug && \
docker-php-ext-enable xdebug

# Désactiver les modules inutiles et optimiser Apache
RUN a2dismod status \
    && a2enmod headers \
    && a2enmod rewrite

# Sécuriser les headers HTTP
RUN echo 'Header always unset X-Powered-By' >> /etc/apache2/conf-enabled/security.conf \
    && echo 'Header always set X-Content-Type-Options "nosniff"' >> /etc/apache2/conf-enabled/security.conf \
    && echo 'Header always set X-XSS-Protection "1; mode=block"' >> /etc/apache2/conf-enabled/security.conf \
    && echo 'Header always set X-Frame-Options "SAMEORIGIN"' >> /etc/apache2/conf-enabled/security.conf

# Copier les fichiers de l'application dans le conteneur
COPY ./api /var/www/html/

# Exposer le port 80 pour le trafic HTTP
EXPOSE 80

# Commande pour démarrer Apache en mode foreground
CMD ["apache2-foreground"]
