
  version: '3.8'

  services:
    # Frontend Service
    frontend:
      image: php:8-apache
      ports:
        - "8083:80"
      volumes:
        - ./front:/var/www/html/
      env_file:
        - .env

    # API Service
    api:
      build: .
      ports:
        - "8082:80"
      volumes:
        - ./api:/var/www/html/

    # Database Service
    db:
      image: mysql:latest
      restart: always
      env_file: 
      - .env
      ports:
        - 3306:3306
      volumes:
      - db-data:/var/lib/mysql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql


    # phpMyAdmin Service
    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      ports:
        - "8086:80"
      env_file: 
      - .env
  volumes:
    db-data: