version: '3.8'

services:
  frontend:
    image: httpd:2.4  
    ports:
      - "8083:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/ 

   # API Service
  api:
    build: .
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www/html/ 

  # pgAdmin Service
  
  # Database Service
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=temps
      - POSTGRES_USER=temps

volumes:
  pgadmin-data:
  db-data: