version: '3.8'

services:
  frontend:
    image: httpd:2.4  
    ports:
      - "8083:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs/ 

  # API Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile  
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html/  

    depends_on:
      - db  

  # Database Service
  db:
    image: mysql:5.7  
    volumes:
      - db-data:/var/lib/mysql  
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=au_temps_donnee  # Database name to create
      - MYSQL_USER=root  # Database user
      - MYSQL_PASSWORD=root  # Database user password
    ports:
      - "3306:3306"  

volumes:
  db-data:  
