version: '3.9'

services:
  # Frontend Service
  frontend:
    image: rg.fr-par.scw.cloud/namespace-temps-donne/ubuntu:dev
    ports:
      - "8083:80"
    volumes:
      - ./front:/var/www/html
    environment:
      - NODE_ENV=development

  # API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:80"
    volumes:
      - ./api:/var/www/html
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=toor
      - DB_NAME=temps

  # Database Service
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: temps
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./bdd.sql:/docker-entrypoint-initdb.d/bdd.sql

volumes:
  db-data:
