version: '3.8'

services:
  administrateurs:
    build:
      context: ./api/Administrateurs
    ports:
      - "8080:80"

  beneficiaire:
    build:
      context: ./api/Beneficiaire
    ports:
      - "8081:80"

  benevole:
    build:
      context: ./api/Benevole
    ports:
      - "8082:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db-data:
