global:
  scrape_interval: 120s
  evaluation_interval: 120s
  external_labels:
      monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Uncomment the following lines if you have an nginx-exporter service
  # - job_name: 'nginx-exporter'
  #   static_configs:
  #     - targets: ['nginx-exporter:9113']
